# Site Settings
baseurl: ""
url : "https://mzaini30.com/labs"

# Blog Settings
theme_settings :
  title : Labs Zen
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Zen
    description : developer Android.
    experience :
      - start : 2015-01-01
        end : 2019-12-13
        experience : freelance, Android developer
    skills : 
      - skill : HTML
        value : 80  # Percent value
      - skill : CSS
        value : 70  # Percent value
      - skill : jQuery
        value : 50  # Percent value
      - skill : Vanilla Javascript
        value : 30  # Percent value
      - skill : Ruby
        value : 10  # Percent value
      - skill : Python
        value : 60  # Percent value
      - skill : Bash
        value : 40  # Percent value
      - skill : Node JS
        value : 5  # Percent value
      - skill : Batch
        value : 80  # Percent value
        
  # Icons
  icons :
    email: muhzaini30@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: mzaini30
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: mzaini30
    youtube:
    facebook: mzaini30
    instagram: mzaini30

  # Disqus
  disqus_shortname : labszen

# Pagination
paginate: 25
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-feed]
bootstrap:
  assets: true
